security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
          App\Entity\User:
              algorithm: bcrypt
    providers:
        user_db:
          entity:
            class: App\Entity\User
            property: username

    access_control:
        - { path: ^/lucky/number, roles: ROLE_USER }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

            provider: user_db
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true

            logout:
                path: /user/logout
                target: home



