index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

user:
    path: /user/login
    defaults: { _controller: 'App\Controller\UserController::login' }

logout:
    path: /user/logout
